In [1]:
import pandas as pd
import os

## What is the difference between SI files and results (standardized) files?

### Standardized datasets:

In [11]:
path_std = '../../data/standardized_data/'
[f for f in os.listdir(path_std) if '.csv' in f and 'result_logfc' in f]

['result_logfc_matrix_2021_11_15_BASIS_mbio.csv',
 'result_logfc_matrix_2021_05_18.csv',
 'result_logfc_matrix_2021_08_27_BASIS.csv',
 'result_logfc_matrix_2020_08_09.csv',
 'result_logfc_matrix_2019_12_10.csv',
 'result_logfc_matrix_2021_10_22.csv',
 'result_logfc_matrix_2021_11_15_BASIS_invitro.csv',
 'result_logfc_matrix_2020_06_27.csv',
 'result_logfc_matrix_2021_11_15_BASIS_mbio_invitro.csv',
 'result_logfc_matrix_2021_08_27.csv',
 'result_logfc_matrix_2021_10_22_BASIS.csv',
 'result_logfc_matrix_2020_08_27.csv']

In [16]:
fn_std = os.path.join(path_std, 'result_logfc_matrix_2021_11_15_BASIS_mbio.csv')
df_std = pd.read_csv(fn_std)
df_std.head(3)

,Rv_ID,PE35_KO_vs_mbio_H37Rv,PPE68_KO_vs_mbio_H37Rv,Rv0950c_KO_vs_CB_WT,Rv0954_KO_vs_RJ_WT,Rv1096_KO_vs_CB_WT,Rv3005c_KO_day32_vs_dejesus_H37Rv_day32,Rv3594_KO_vs_Rubin_FLUTE_WT,Rv3684_KO_vs_CB_WT,Rv3717_KO_vs_Rubin_FLUTE_WT,...,Cast.EiJ_vs_mbio_H37Rv,IFNG_vs_mbio_H37Rv,NOD.ShiLtJ_vs_mbio_H37Rv,NOS_vs_mbio_H37Rv,NZO.H1LtJ_vs_mbio_H37Rv,PWK.PhJ_vs_mbio_H37Rv,Phox_vs_mbio_H37Rv,Rag_vs_mbio_H37Rv,Wsb.Eij_vs_mbio_H37Rv,in_vitro_vs_mbio_H37Rv
0,Rv0001,-0.41,0.01,0.00,0.0,0.00,3.12,-0.06,0.00,-0.06,...,-0.18,-0.18,-0.18,-0.18,-0.18,0.04,-0.18,-0.18,-0.18,-0.18
1,Rv0002,3.28,2.38,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,-0.07,-0.07,-0.07,-0.07,-0.07,-0.07,-0.07,-0.07,0.20,-0.07
2,Rv0003,-0.03,-0.08,0.03,-1.2,0.39,3.83,0.31,0.17,-0.62,...,-3.37,-2.36,-1.89,-2.25,-2.14,-3.21,-2.79,-3.20,-2.33,-2.77

In [18]:
print(df_std.shape)
df_std.columns[:50]

(4055, 126)

Index(['Rv_ID', 'PE35_KO_vs_mbio_H37Rv', 'PPE68_KO_vs_mbio_H37Rv',
       'Rv0950c_KO_vs_CB_WT', 'Rv0954_KO_vs_RJ_WT', 'Rv1096_KO_vs_CB_WT',
       'Rv3005c_KO_day32_vs_dejesus_H37Rv_day32',
       'Rv3594_KO_vs_Rubin_FLUTE_WT', 'Rv3684_KO_vs_CB_WT',
       'Rv3717_KO_vs_Rubin_FLUTE_WT', 'Rv3811_KO_vs_Rubin_FLUTE_WT',
       'bellerose_MB_HRZE_wk1_vs_bellerose_MB_d21_untreated',
       'bellerose_MB_HRZE_wk1_vs_bellerose_MB_pretreatment',
       'bellerose_MB_d21_untreated_vs_bellerose_MB_pretreatment',
       'carey_621_vs_carey_rv', 'carey_630_vs_carey_rv',
       'carey_631_vs_carey_rv', 'carey_632_vs_carey_rv',
       'carey_641_vs_carey_rv', 'carey_662_vs_carey_rv',
       'carey_663_vs_carey_rv', 'carey_667_vs_carey_rv',
       'dejesus_H37Rv_day32_vs_dejesus_H37Rv_day0',
       'dejesus_Rv0307c_day32_vs_dejesus_Rv0307c_day0',
       'dejesus_Rv1432_day0_vs_dejesus_H37Rv_day0',
       'dejesus_Rv1432_day32_vs_dejesus_H37Rv_day32',
       'dejesus_Rv1432_day32_vs_dejesus_Rv1432_day0',
       'dejesus_Rv1565c_day0_vs_dejesus_H37Rv_day0',
       'dejesus_Rv1565c_day32_vs_dejesus_H37Rv_day32',
       'dejesus_Rv1565c_day32_vs_dejesus_Rv1565c_day0',
       'dejesus_Rv2680_day0_vs_dejesus_H37Rv_day0',
       'dejesus_Rv2680_day32_vs_dejesus_H37Rv_day32',
       'dejesus_Rv2680_day32_vs_dejesus_Rv2680_day0',
       'dejesus_Rv3916c_day32_vs_dejesus_Rv3916c_day0',
       'eccD1_KO_vs_mbio_H37Rv', 'espI_KO_vs_mbio_H37Rv',
       'griffin_cholesterol_vs_griffin_glycerol',
       'griffin_glycerol_vs_mbio_H37Rv', 'kieser_dPonA1_vs_mbio_H37Rv',
       'korte_2016_otsa_trehalose_vs_korte_2016_otsa_7h9',
       'marP_KO_vs_marP_WT', 'minato_minimal_plate_vs_minato_rich_plate',
       'mishra_C3H_vs_mishra_B6', 'mishra_NOS2_vs_mishra_B6',
       'mishra_NOS2_vs_mishra_C3H', 'nambi_2015_ctpC_vs_nambi_2015_wt',
       'ritterhaus_hypoxia_H3_vs_ritterhaus_hypoxia_input',
       'ritterhaus_hypoxia_H6_vs_ritterhaus_hypoxia_input',
       'xu_emb_2.5_vs_xu_emb_0', 'xu_emb_3_vs_xu_emb_0'],
      dtype='object')

### SI datasets:

In [5]:
path_SI = '../../data/SI_datasets/'
[f for f in os.listdir(path_SI) if '.csv' in f and 'SI' in f]

['SI_qval.csv',
 'SI_bin.csv',
 'SI_qval_bxd.csv',
 'SI_log2FC_bxd.csv',
 'SI_log2FC.csv']

In [13]:
fn_SI = os.path.join(path_SI, 'SI_log2FC.csv')
df_SI = pd.read_csv(fn_SI)
df_SI.head(3)

,Rv_ID,gene_name,2003A_Sassetti,2003B_Sassetti,2005_Rengarajan,2006_Joshi_GI_1,2006_Joshi_GI_2,2011_Griffin_2,2013_Zhang_1A,2013_Zhang_1B,...,2018_Carey_1B,2018_Carey_1C,2018_Carey_1D,2018_Carey_1E,2018_Carey_1F,2018_Carey_1G,2018_Carey_1H,2017B_DeJesus_1A,2017B_DeJesus_1B,2017B_DeJesus_1C
0,Rv0001,dnaA,-3.378401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,-0.05,4.53,0.00,0.00,2.14,0.0,-0.60,-1.02,-0.72
1,Rv0002,dnaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,-0.60,-1.00,-0.72
2,Rv0003,recF,NaN,NaN,NaN,NaN,NaN,NaN,-6.211402,-3.223423,...,0.03,-0.64,-0.49,-0.09,-0.31,0.03,-0.2,-0.41,0.45,-0.37

In [19]:
print(df_SI.shape)
df_SI.columns[:50]

(3990, 42)

Index(['Rv_ID', 'gene_name', '2003A_Sassetti', '2003B_Sassetti',
       '2005_Rengarajan', '2006_Joshi_GI_1', '2006_Joshi_GI_2',
       '2011_Griffin_2', '2013_Zhang_1A', '2013_Zhang_1B', '2013_Zhang_2',
       '2013_Zhang_3A', '2013_Zhang_3B', '2013_Zhang_3C', '2013_Zhang_3D',
       '2016_Korte', '2018_Rittershaus_1A', '2018_Rittershaus_1B',
       '2012_Zhang', '2015_Kieser_GI_1', '2015_Kieser_GI_2',
       '2015_Kieser_GI_3', '2015_Mendum', '2016_Nambi', '2017_Mishra_1',
       '2017_Mishra_2', '2017_Xu_1A', '2017_Xu_1B', '2017_Xu_1C', '2017_Xu_1D',
       '2017_Xu_1E', '2018_Carey_1A', '2018_Carey_1B', '2018_Carey_1C',
       '2018_Carey_1D', '2018_Carey_1E', '2018_Carey_1F', '2018_Carey_1G',
       '2018_Carey_1H', '2017B_DeJesus_1A', '2017B_DeJesus_1B',
       '2017B_DeJesus_1C'],
      dtype='object')