## Join matrices

In [12]:
import pandas as pd
import os
import numpy as np

In [4]:
path = '../data/'
matrix=pd.read_excel(os.path.join(path, 'Tn_library_log2FC_DASH.xlsx'))
matrix.head()

,Rv_ID,gene_name,2012_Zhang_log2FC,2015_Kieser_GI_1_log2FC,2015_Kieser_GI_2_log2FC,2015_Kieser_GI_3_log2FC,2015_Mendum_log2FC,2016_Nambi_log2FC,2017_Xu_1A_log2FC,2017_Xu_1B_log2FC,...,ponA1_log2FC,Rv1565c_log2FC,Rv3684_log2FC,Rv0954_log2FC,Rv3811_log2FC,Rv1096_log2FC,Rv2680_log2FC,Rv1432_log2FC,Rv3594_log2FC,Rv3005c_log2FC
0,Rv0001,dnaA,NaN,1.242756,1.584963,-0.213880,NaN,NaN,0.000000,0.000000,...,2.21,3.83,0.00,0.00,1.18,0.00,-0.10,3.83,0.00,3.37
1,Rv0002,dnaN,NaN,-0.574319,1.584963,-1.772497,NaN,NaN,0.000000,0.000000,...,2.21,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,Rv0003,recF,NaN,0.913190,0.439142,-0.452153,NaN,0.599232,-0.535596,-0.549777,...,-0.40,2.81,0.17,-1.20,0.48,0.39,-1.93,1.50,0.31,3.45
3,Rv0004,-,NaN,0.021994,-1.119820,-2.945263,NaN,1.515639,0.000000,0.000000,...,-2.66,0.00,1.08,-6.83,2.61,1.54,0.00,0.00,1.79,0.00
4,Rv0005,gyrB,NaN,3.108722,4.087463,-0.905491,NaN,-1.948935,0.000000,0.000000,...,-0.97,-0.52,-0.71,-0.08,0.04,0.27,-2.30,-5.08,0.70,-5.19

In [5]:
matrix=pd.melt(matrix, id_vars=['Rv_ID', 'gene_name'], var_name='Expt', value_name='log2FC')

In [6]:
matrix['Expt']=matrix['Expt'].str.replace('_log2FC', "")

In [7]:
matrix=matrix[~matrix['log2FC'].isnull()]

In [8]:
qvals=pd.read_excel(os.path.join(path, 'Tn_library_qvals_DASH.xlsx'))
qvals.head()

,Rv_ID,gene_name,2012_Zhang_q_val,2015_Kieser_GI_1_q_val,2015_Kieser_GI_2_q_val,2015_Kieser_GI_3_q_val,2015_Mendum_q_val,2016_Nambi_q_val,2017_Xu_1A_q_val,2017_Xu_1B_q_val,...,ponA1_q_val,Rv1565c_q_val,Rv3684_q_val,Rv0954_q_val,Rv3811_q_val,Rv1096_q_val,Rv2680_q_val,Rv1432_q_val,Rv3594_q_val,Rv3005c_q_val
0,Rv0001,dnaA,0.0088,0.273069,0.081529,0.605682,NaN,NaN,1.0,1.0,...,1.0,1.0,1.0,1.00000,1.0,1.0,1.00000,1.00000,1.0,0.75078
1,Rv0002,dnaN,0.0009,0.753480,0.160688,0.654277,NaN,NaN,1.0,1.0,...,1.0,1.0,1.0,1.00000,1.0,1.0,1.00000,1.00000,1.0,1.00000
2,Rv0003,recF,0.1151,0.607459,0.545435,0.366102,0.308320,0.414519,1.0,1.0,...,1.0,0.0,1.0,0.38260,1.0,1.0,0.42468,0.69974,1.0,0.49222
3,Rv0004,-,NaN,0.909333,1.000000,1.000000,0.037242,NaN,1.0,1.0,...,1.0,1.0,1.0,0.98049,1.0,1.0,1.00000,1.00000,1.0,1.00000
4,Rv0005,gyrB,0.0088,0.489834,0.081947,0.722442,NaN,0.330393,1.0,1.0,...,1.0,1.0,1.0,1.00000,1.0,1.0,0.39119,0.46795,1.0,0.38872

In [9]:
qvals=pd.melt(qvals, id_vars=['Rv_ID', 'gene_name'], var_name='Expt', value_name='q-val')
qvals['Expt']=qvals['Expt'].str.replace('_q_val', "")
qvals.head()

    Rv_ID gene_name        Expt   q-val
0  Rv0001      dnaA  2012_Zhang  0.0088
1  Rv0002      dnaN  2012_Zhang  0.0009
2  Rv0003      recF  2012_Zhang  0.1151
3  Rv0004         -  2012_Zhang     NaN
4  Rv0005      gyrB  2012_Zhang  0.0088

In [10]:
final=pd.merge(matrix,qvals, how='left', on=['Rv_ID', 'Expt', 'gene_name'])

In [13]:
final[final['log2FC']==-np.inf]

         Rv_ID gene_name              Expt  log2FC  q-val
148    Rv0150c         -  2015_Kieser_GI_1    -inf    1.0
428     Rv0430         -  2015_Kieser_GI_1    -inf    1.0
629     Rv0627         -  2015_Kieser_GI_1    -inf    1.0
685     Rv0682      rpsL  2015_Kieser_GI_1    -inf    1.0
686     Rv0683      rpsG  2015_Kieser_GI_1    -inf    1.0
708     Rv0705      rpsS  2015_Kieser_GI_1    -inf    1.0
712     Rv0709      rpmC  2015_Kieser_GI_1    -inf    1.0
718     Rv0715      rplX  2015_Kieser_GI_1    -inf    1.0
720     Rv0717      rpsN  2015_Kieser_GI_1    -inf    1.0
768    Rv0763c         -  2015_Kieser_GI_1    -inf    1.0
793    Rv0787A         -  2015_Kieser_GI_1    -inf    1.0
813     Rv0807         -  2015_Kieser_GI_1    -inf    1.0
889    Rv0883c         -  2015_Kieser_GI_1    -inf    1.0
985    Rv0979A      rpmF  2015_Kieser_GI_1    -inf    1.0
1101    Rv1093      glyA  2015_Kieser_GI_1    -inf    1.0
1315    Rv1306      atpF  2015_Kieser_GI_1    -inf    1.0
1318    Rv1309      atpG  2015_Kieser_GI_1    -inf    1.0
1320    Rv1311      atpC  2015_Kieser_GI_1    -inf    1.0
1390    Rv1382         -  2015_Kieser_GI_1    -inf    1.0
1391    Rv1383      carA  2015_Kieser_GI_1    -inf    1.0
1471    Rv1463         -  2015_Kieser_GI_1    -inf    1.0
1474    Rv1466         -  2015_Kieser_GI_1    -inf    1.0
1586    Rv1573         -  2015_Kieser_GI_1    -inf    1.0
1589   Rv1576c         -  2015_Kieser_GI_1    -inf    1.0
1607    Rv1594      nadA  2015_Kieser_GI_1    -inf    1.0
1624    Rv1611      trpC  2015_Kieser_GI_1    -inf    1.0
1656    Rv1642      rpmI  2015_Kieser_GI_1    -inf    1.0
1669    Rv1655      argD  2015_Kieser_GI_1    -inf    1.0
1670    Rv1656      argF  2015_Kieser_GI_1    -inf    1.0
1957   Rv1942c         -  2015_Kieser_GI_1    -inf    1.0
...        ...       ...               ...     ...    ...
10850  Rv2921c      ftsY  2015_Kieser_GI_3    -inf    1.0
10855  Rv2925c       rnc  2015_Kieser_GI_3    -inf    1.0
10908  Rv2977c      thiL  2015_Kieser_GI_3    -inf    1.0
10934  Rv3003c     ilvB1  2015_Kieser_GI_3    -inf    1.0
10940  Rv3009c      gatB  2015_Kieser_GI_3    -inf    1.0
10961   Rv3030         -  2015_Kieser_GI_3    -inf    1.0
11149   Rv3219     whiB1  2015_Kieser_GI_3    -inf    1.0
11159   Rv3227      aroA  2015_Kieser_GI_3    -inf    1.0
11178  Rv3246c      mtrA  2015_Kieser_GI_3    -inf    1.0
11192  Rv3260c     whiB2  2015_Kieser_GI_3    -inf    1.0
11207  Rv3275c      purE  2015_Kieser_GI_3    -inf    1.0
11208  Rv3276c      purK  2015_Kieser_GI_3    -inf    1.0
11356  Rv3422c         -  2015_Kieser_GI_3    -inf    1.0
11376  Rv3442c      rpsI  2015_Kieser_GI_3    -inf    1.0
11396  Rv3462c      infA  2015_Kieser_GI_3    -inf    1.0
11399   Rv3465      rmlC  2015_Kieser_GI_3    -inf    1.0
11516  Rv3581c      ispF  2015_Kieser_GI_3    -inf    1.0
11523  Rv3588c         -  2015_Kieser_GI_3    -inf    1.0
11532  Rv3597c      lsr2  2015_Kieser_GI_3    -inf    1.0
11538  Rv3603c         -  2015_Kieser_GI_3    -inf    1.0
11544  Rv3609c      folE  2015_Kieser_GI_3    -inf    1.0
11589  Rv3654c         -  2015_Kieser_GI_3    -inf    1.0
11608  Rv3673c         -  2015_Kieser_GI_3    -inf    1.0
11645  Rv3708c       asd  2015_Kieser_GI_3    -inf    1.0
11690  Rv3752c         -  2015_Kieser_GI_3    -inf    1.0
11707   Rv3769         -  2015_Kieser_GI_3    -inf    1.0
11718  Rv3778c         -  2015_Kieser_GI_3    -inf    1.0
11721   Rv3781      rfbE  2015_Kieser_GI_3    -inf    1.0
11801   Rv3861         -  2015_Kieser_GI_3    -inf    1.0
11864  Rv3924c      rpmH  2015_Kieser_GI_3    -inf    1.0

[290 rows x 5 columns]

In [14]:
final.to_csv('Tn_library_DASH.csv', index=False)

## Join cogs

In [37]:
cogs=pd.read_csv('all_cogs.csv')
cog_names=pd.read_csv('cog_names.csv')

In [38]:
cogs.head()

    X.Orf COG
0  Rv0001   L
1  Rv0002   L
2  Rv0003   L
3  Rv0004   R
4  Rv0005   L

In [39]:
cog_names.head()

  COG                                           COG_Desc
0   L             Replication, recombination and repair
1   R                  General function prediction only
2   O  Posttranslational modification, protein turnov...
3   S                                  Function unknown
4   H                 Coenzyme transport and metabolism

In [40]:
merged_cogs=pd.merge(cogs, cog_names, how='left', on='COG')

In [46]:
merged_cogs['COG_Desc'].isnull().any()

False

In [48]:
merged_cogs.to_csv('all_cogs_desc.csv', index=False)